---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: "Install nodejs version 13.8.0"
  become: yes
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to use Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0

- name : "Install pm2 using npm"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: Create a directory if it does not exist
#   ansible.builtin.file:
#     path: ~/web
#     state: directory
#     mode: '0755'

# - name: Copy index test page
#   copy:
#     src: "files/index.js"
#     dest: "~/web/index.js"
#     owner: ubuntu
#     group: ubuntu        
#     mode: 0644

# - name: Executing node
#   shell: |
#     pm2 start ~/web/index.js -f

